


[aws]
symbol = "  "

[character]
format = "$symbol "
success_symbol = "[NOR ❯](bold green)"
error_symbol = "[NOR ❯](bold red)"
vicmd_symbol = "[CMD ❮](bold blue)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

