use-grammars = { except = ["gemini"] }

[language-server.ruff]
command = "ruff"
args = ["server", "--config","line-length=80"]

[[language]]
name = "python"
scope = "source.python"
language-servers = [ "ruff" ]

