[tools]
usage = "latest"

[tasks.pyvenv]
# python{{arg(name="version", var="3")}} -m venv .venv
run="""
python3 -m venv .venv
(
  source .venv/bin/activate
  pip install --upgrade pip
  [[ -e ./requirements.txt ]] && pip install -r requirements.txt
  pip install ruff-lsp
)
touch .mise.toml
mise trust --show | grep -q 'untrusted' && mise trust -y .mise.toml
mise toml set -y env._\\.python\\.venv\\.path .venv
mise toml set -y -t bool env._\\.python\\.venv\\.create true
"""

[tasks.backup-home]
dir = "{{ env.HOME }}"
run="""
  op whoami >/dev/null 2>/dev/null || eval "$(op signin)" && \
  restic init \
    --password-command 'op read "{{ option(name='passphrase_secret_ref', default='op://Local Cluster/Restic Backup Passphrase/password') }}"' \
    -r {{ option(name='repo') }} \
    >/dev/null 2>/dev/null; \
  restic backup \
    --password-command 'op read "{{ option(name='passphrase_secret_ref', default='op://Local Cluster/Restic Backup Passphrase/password') }}"' \
    -r {{ option(name='repo') }} \
    -e .1password \
    -e .airshipsgame \
    -e .ansible \
    -e .bash_history \
    -e .bash_logout \
    -e .bashrc.d \
    -e .cache \
    -e .cargo \
    -e .cert \
    -e .config \
    -e .factorio \
    -e .font \
    -e .fonts.conf \
    -e .fzf \
    -e .fzf.bash \
    -e .gitconfig \
    -e .gnupg \
    -e .gtkrc-2.0 \
    -e .guestfish \
    -e .java \
    -e .local \
    -e .mozilla \
    -e .openjfx \
    -e .paradoxlauncher \
    -e .pki \
    -e .pulse-cookie \
    -e .python_history \
    -e .rustup \
    -e .ssh \
    -e .steam \
    -e .terraform.d \
    -e .wget-hsts \
    -e **/.git \
    -e **/.github \
    -e **.egg \
    -e **.egg-info \
    --iexclude projects/virtual-infrastructure \
    --iexclude projects/setups \
    --iexclude admin \
    --iexclude **/games \
    --iexclude **/download \
    --iexclude **/downloads \
    --iexclude **/downloading \
    --iexclude **/toprocess \
    --iexclude **/to-process \
    --iexclude **/to-processes \
    --iexclude **/toprocesses \
    --iexclude **/tmp \
    --iexclude **/venv \
    --iexclude **/.venv \
    --iexclude **.pyc \
    --iexclude **backup** \
    --iexclude **bkup** \
    ./
"""
